model = "gpt-5.2-codex-max"
review_model = "gpt-5.2-codex-max"
model_reasoning_effort = "xhigh"
approval_policy = "never"
sandbox_mode = "danger-full-access"

[sandbox_workspace_write]
network_access = true

[features]
shell_snapshot = true
web_search_request = true

[analytics]
enabled = false

[feedback]
enabled = false